name = "Tufte CSS"
license = "MIT"
licenselink = "https://github.com/alanorth/hugo-theme-tufte-css/blob/master/LICENSE.md"
description = "A simple Hugo theme based on the Tufte CSS style."
homepage = "https://github.com/alanorth/hugo-theme-tufte-css"
tags = ["blog"]
features = ["responsive", "blog"]
min_version = 0.18

[author]
  name = "Alan Orth"
  homepage = "https://github.com/alanorth/"

# If porting an existing theme
[original]
  name = "Tufte CSS"
  homepage = "https://edwardtufte.github.io/tufte-css/"
  repo = "https://github.com/edwardtufte/tufte-css.git"
